services:
  postgres:
    image: postgres:15-alpine
    container_name: music_market_db
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - music_network

  adminer:
    image: adminer:latest
    container_name: music_market_adminer
    restart: unless-stopped
    ports:
      - "8088:8080"
    depends_on:
      - postgres
    networks:
      - music_network

volumes:
  postgres_data:

networks:
  music_network:
    driver: bridge
