-- ======================================================
-- MUSIC MARKET POSTGRESQL DDL
-- Rule:
-- - users.user_id uses UUID
-- - Business entities use BIGINT auto increment (GENERATED BY DEFAULT AS IDENTITY)
-- - FKs referencing users.user_id are UUID
-- ======================================================

-- Enable pgcrypto for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ======================================================
-- ENUM TYPES
-- ======================================================

CREATE TYPE user_role AS ENUM (
  'admin', 
  'producer'
);

CREATE TYPE track_status AS ENUM (
  'draft', 
  'published', 
  'reserved', 
  'sold_non_exclusive', 
  'sold_exclusive', 
  'hidden', 
  'archived'
);

CREATE TYPE audio_file_type AS ENUM (
  'preview', 
  'watermarked_preview', 
  'original', 
  'stem'
);

CREATE TYPE inquiry_status AS ENUM (
  'new', 
  'contacted', 
  'negotiating', 
  'waiting_payment', 
  'paid', 
  'delivered', 
  'closed', 
  'rejected'
);

CREATE TYPE purchase_status AS ENUM (
  'pending', 
  'paid', 
  'delivered', 
  'completed', 
  'cancelled', 
  'refunded'
);

CREATE TYPE usage_purpose AS ENUM (
  'personal_demo', 
  'commercial_release', 
  'youtube_tiktok', 
  'advertising', 
  'film_game', 
  'live_performance', 
  'brand_campaign', 
  'other'
);

-- ======================================================
-- TABLES
-- ======================================================

-- 1. USERS
CREATE TABLE users (
  user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role user_role NOT NULL DEFAULT 'admin',
  avatar_url TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 2. TRACKS
CREATE TABLE tracks (
  track_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id UUID NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  bpm INTEGER CHECK (bpm > 0 AND bpm <= 300),
  musical_key VARCHAR(20),
  duration_seconds INTEGER CHECK (duration_seconds >= 0),
  cover_image_url TEXT,
  preview_audio_url TEXT,
  status track_status NOT NULL DEFAULT 'draft',
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  allow_inquiry BOOLEAN NOT NULL DEFAULT TRUE,
  view_count INTEGER NOT NULL DEFAULT 0,
  play_count INTEGER NOT NULL DEFAULT 0,
  inquiry_count INTEGER NOT NULL DEFAULT 0,
  published_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  deleted_at TIMESTAMP
);

-- Indexes for tracks
CREATE INDEX idx_tracks_status ON tracks(status);
CREATE INDEX idx_tracks_owner_id ON tracks(owner_id);
CREATE INDEX idx_tracks_bpm ON tracks(bpm);
CREATE INDEX idx_tracks_created_at ON tracks(created_at);
CREATE INDEX idx_tracks_published_at ON tracks(published_at);

-- 3. GENRES
CREATE TABLE genres (
  genre_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  genre_name VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 4. TRACK GENRES (Many-to-Many)
CREATE TABLE track_genres (
  track_id BIGINT NOT NULL REFERENCES tracks(track_id) ON DELETE CASCADE,
  genre_id BIGINT NOT NULL REFERENCES genres(genre_id) ON DELETE CASCADE,
  PRIMARY KEY (track_id, genre_id)
);

-- 5. MOODS
CREATE TABLE moods (
  mood_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mood_name VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 6. TRACK MOODS (Many-to-Many)
CREATE TABLE track_moods (
  track_id BIGINT NOT NULL REFERENCES tracks(track_id) ON DELETE CASCADE,
  mood_id BIGINT NOT NULL REFERENCES moods(mood_id) ON DELETE CASCADE,
  PRIMARY KEY (track_id, mood_id)
);

-- 7. TAGS
CREATE TABLE tags (
  tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_name VARCHAR(100) NOT NULL UNIQUE,
  slug VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 8. TRACK TAGS (Many-to-Many)
CREATE TABLE track_tags (
  track_id BIGINT NOT NULL REFERENCES tracks(track_id) ON DELETE CASCADE,
  tag_id BIGINT NOT NULL REFERENCES tags(tag_id) ON DELETE CASCADE,
  PRIMARY KEY (track_id, tag_id)
);

-- 9. AUDIO FILES
CREATE TABLE track_audio_files (
  audio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id BIGINT NOT NULL REFERENCES tracks(track_id) ON DELETE CASCADE,
  file_type audio_file_type NOT NULL,
  file_url TEXT NOT NULL,
  file_name VARCHAR(255),
  mime_type VARCHAR(100),
  file_size_bytes BIGINT,
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  is_downloadable BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Indexes for track_audio_files
CREATE INDEX idx_track_audio_files_track_id ON track_audio_files(track_id);
CREATE INDEX idx_track_audio_files_type ON track_audio_files(file_type);

-- 10. LICENSE PLANS
CREATE TABLE license_plans (
  license_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  license_name VARCHAR(150) NOT NULL,
  slug VARCHAR(150) NOT NULL UNIQUE,
  description TEXT,
  usage_rights TEXT,
  is_exclusive BOOLEAN NOT NULL DEFAULT FALSE,
  default_price DECIMAL(12,2),
  currency VARCHAR(10) NOT NULL DEFAULT 'VND',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- 11. TRACK LICENSE OPTIONS
CREATE TABLE track_license_options (
  license_option_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id BIGINT NOT NULL REFERENCES tracks(track_id) ON DELETE CASCADE,
  license_plan_id BIGINT NOT NULL REFERENCES license_plans(license_id) ON DELETE CASCADE,
  price DECIMAL(12,2),
  currency VARCHAR(10) NOT NULL DEFAULT 'VND',
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  custom_terms TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_track_license_plan UNIQUE (track_id, license_plan_id)
);

CREATE INDEX idx_track_license_options_track_id ON track_license_options(track_id);

-- 12. CUSTOMERS
CREATE TABLE customers (
  customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name VARCHAR(150) NOT NULL,
  customer_email VARCHAR(255),
  customer_phone VARCHAR(50),
  company_name VARCHAR(255),
  social_link TEXT,
  note TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT customer_contact_required CHECK (customer_email IS NOT NULL OR customer_phone IS NOT NULL)
);

CREATE INDEX idx_customers_email ON customers(customer_email);
CREATE INDEX idx_customers_phone ON customers(customer_phone);

-- 13. PURCHASE INQUIRIES
CREATE TABLE purchase_inquiries (
  purchase_inquiry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
  preferred_license_option_id BIGINT REFERENCES track_license_options(license_option_id) ON DELETE SET NULL,
  usage_purpose usage_purpose,
  usage_description TEXT,
  budget DECIMAL(12,2),
  currency VARCHAR(10) DEFAULT 'VND',
  message TEXT,
  status inquiry_status NOT NULL DEFAULT 'new',
  admin_note TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_purchase_inquiries_customer_id ON purchase_inquiries(customer_id);
CREATE INDEX idx_purchase_inquiries_status ON purchase_inquiries(status);
CREATE INDEX idx_purchase_inquiries_created_at ON purchase_inquiries(created_at);

-- 14. INQUIRY TRACKS (Many-to-Many)
CREATE TABLE inquiry_tracks (
  inquiry_id BIGINT NOT NULL REFERENCES purchase_inquiries(purchase_inquiry_id) ON DELETE CASCADE,
  track_id BIGINT NOT NULL REFERENCES tracks(track_id) ON DELETE CASCADE,
  PRIMARY KEY (inquiry_id, track_id)
);

-- 15. PURCHASES
CREATE TABLE purchases (
  purchase_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inquiry_id BIGINT REFERENCES purchase_inquiries(purchase_inquiry_id) ON DELETE SET NULL,
  customer_id BIGINT NOT NULL REFERENCES customers(customer_id) ON DELETE CASCADE,
  track_id BIGINT NOT NULL REFERENCES tracks(track_id) ON DELETE CASCADE,
  license_option_id BIGINT REFERENCES track_license_options(license_option_id) ON DELETE SET NULL,
  license_name VARCHAR(150) NOT NULL,
  is_exclusive BOOLEAN NOT NULL DEFAULT FALSE,
  final_price DECIMAL(12,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'VND',
  status purchase_status NOT NULL DEFAULT 'pending',
  contract_url TEXT,
  delivered_file_url TEXT,
  paid_at TIMESTAMP,
  delivered_at TIMESTAMP,
  completed_at TIMESTAMP,
  note TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Partial Unique Index for purchases:
-- Only one paid/delivered/completed exclusive purchase is allowed per track.
CREATE UNIQUE INDEX idx_purchases_exclusive_paid_completed_unique 
ON purchases (track_id) 
WHERE (is_exclusive = TRUE AND status IN ('paid', 'delivered', 'completed'));

CREATE INDEX idx_purchases_customer_id ON purchases(customer_id);
CREATE INDEX idx_purchases_track_id ON purchases(track_id);
CREATE INDEX idx_purchases_status ON purchases(status);
CREATE INDEX idx_purchases_created_at ON purchases(created_at);

-- 16. PLAY EVENTS
CREATE TABLE track_play_events (
  play_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  track_id BIGINT NOT NULL REFERENCES tracks(track_id) ON DELETE CASCADE,
  customer_id BIGINT REFERENCES customers(customer_id) ON DELETE SET NULL,
  ip_address VARCHAR(100),
  user_agent TEXT,
  referrer TEXT,
  played_seconds INTEGER CHECK (played_seconds >= 0),
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_track_play_events_track_id ON track_play_events(track_id);
CREATE INDEX idx_track_play_events_created_at ON track_play_events(created_at);


-- ======================================================
-- AUTOMATIC UPDATED_AT TRIGGER
-- ======================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_users_modtime BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_tracks_modtime BEFORE UPDATE ON tracks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_license_plans_modtime BEFORE UPDATE ON license_plans FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_track_license_options_modtime BEFORE UPDATE ON track_license_options FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_customers_modtime BEFORE UPDATE ON customers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_purchase_inquiries_modtime BEFORE UPDATE ON purchase_inquiries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_purchases_modtime BEFORE UPDATE ON purchases FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
